# Generated by Django 6.0.7 on 2026-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_india', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='About_video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About_image')),
            ],
        ),
    ]
