# Generated by Django 6.0.7 on 2026-08-07 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('State_image', models.ImageField(blank=True, null=True, upload_to='About_state_image')),
                ('location', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
