# Generated by Django 6.1 on 2026-08-16 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('State_name', models.CharField(max_length=70)),
                ('State_description', models.TextField()),
                ('State_img', models.ImageField(blank=True, null=True, upload_to='State_image')),
                ('State_loc_img', models.ImageField(blank=True, null=True, upload_to='State_loc_img')),
                ('State_video', models.FileField(blank=True, null=True, upload_to='State_vedio')),
            ],
        ),
    ]
